### ISSUE TITLE
Where should I add the css js code?

### ISSUE THREAD

**Issue by logoslee** [app-generator/django-soft-ui-dashboard#1]
Hello, I am a student attending a university in Korea. I'm working on a personal project to make Iot dasboard using your dashboard. I just started studying coding, so I'd really appreciate it if you could answer some questions. I want to add various styles to the dashboard using codepen, but I don't know what to refer to. Can you tell me in detail even if you are busy? Thank you for reading it. I look forward to hearing from you.

**Comment by app-generator** [comment]
Hello @logoslee

Ty for even consider using our products. 

To add new CSS/JS save the files in the `core/static/assets` folder.

- Create/save your CSS file in `core/static/assets/css`
- Create/save your JS file in `core/static/assets/js`

Later in the page, you should add the new files in the specific blocks: 

For instance, if you want to use new **JS / CSS** files for [billing.htm](https://github.com/app-generator/django-soft-ui-dashboard/blob/master/core/templates/billing.html). 

```html
{% extends 'layouts/base.html' %}

{% block title %} Billing {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

<link href="/static/assets/css/NEW_CSS_FILE.css" rel="stylesheet" />

{% endblock stylesheets %}

{% block content %}

....

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

<script src="/static/assets/js/NEW_JS_FILE.js"></script>

{% endblock javascripts %}

```
