### ISSUE TITLE
dark mode sidebar and admin filter are hard to see

### ISSUE THREAD

**Issue by matlads** [app-generator/django-soft-ui-dashboard#10]

**Comment by app-generator** [comment]
Hello @matlads 

Thank you for using our products. 

Please provide more input or a screen shot. 

Thank you!

**Comment by matlads** [comment]
![image](https://github.com/app-generator/django-soft-ui-dashboard/assets/507861/ce2eea42-66f1-4d26-be04-82efc16147ff)

see the screenshot referenced.

**Comment by matlads** [comment]
![image](https://github.com/app-generator/django-soft-ui-dashboard/assets/507861/cd84fc30-715c-4200-bbc0-aadc2381875e)

see filter on the right hand side

**Comment by app-generator** [comment]
Hello @matlads 

The admin section looks not so nice. 

yep, we will take a look.
