### ISSUE TITLE
Header overlapping sidebar

### ISSUE THREAD

**Issue by mashfadel** [app-generator/django-soft-ui-dashboard#2]
Hello,

I came across a bug in the pro version of soft-ui-dashboard where in mobile mode, the header overlaps the sidebar. This is due to the header being fixed, but still, I'll always want the header to be fixed so the problem will always exist. Please let me know what's the fix or when there'll be one - thanks.
<img width="168" alt="Screen Shot 2021-11-06 at 8 22 36 PM" src="https://user-images.githubusercontent.com/92476414/140640979-2da832b7-17f0-428b-9be4-ead618c42391.png">

**Comment by app-generator** [comment]
hello @mashfadel 

Fixed in the latest version.
Please update.
