### ISSUE TITLE
Profile menu items

### ISSUE THREAD

**Issue by mashfadel** [app-generator/django-soft-ui-dashboard#3]
This is an issue within the pro version: the highlighted chosen menu items between App, Messages, Settings is misplaced in the Profile pages when you are in mobile mode. Please let me know what's the fix or when there'll be one - thanks.
<img width="168" alt="Screen Shot 2021-11-06 at 9 46 09 PM" src="https://user-images.githubusercontent.com/92476414/140641043-e4375f58-9121-4ddd-812a-2954bc2bcfce.png">

**Comment by app-generator** [comment]
Fixed in the latest version.
Please update.
