### ISSUE TITLE
How to disable aside sidebar in large screen size

### ISSUE THREAD

**Issue by AlexanderVino** [app-generator/django-soft-ui-dashboard#4]
![Screenshot from 2022-02-19 12-24-26](https://user-images.githubusercontent.com/4943393/154795096-d2d9bbb2-e4dd-4a9a-9b8c-ddf7503fc445.jpg)
Hello! Wonderful job for the dashboard! But is it possible to make the sidebar menu behavior in large screens similar to mobile? So it s primarily hidden. And just to click on the menu icon to show it? As it s now working on mobile. Thank you.

**Comment by app-generator** [comment]
Fixed in the latest version.
Please update.
