### ISSUE TITLE
ENH - Django mini eCommerce with Stripe Integration

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-soft-ui-dashboard#5]
The codebase should be enhanced with a minimal eCommerce module that manages products and sales.

Here are the requirements:

- Products table: id (PK), name, info, full description, price, currency, payment
- Sales table: id (PK), productId, value, fees, quantity, timestamp, client, note

The payments are managed by Stripe based on the product payment type:

- payment = 0 (default value), the payment is one-time
- payment = 1, the payment is recurrent (monthly frequency)

The Stripe Secrets are provided in the ".env" and managed by the project configuration.

What the developer should deliver:

**Feature 1** - Use the existing UI and code pages:  

- product creation/update page (factorized using a single page)
- product index page, where all products are listed

**Feature 2** - Sales

- values are inserted by Stripe post-sale callback (finished or canceled sales)
- page where the sales are listed using a data table
- the data tables layout provides an edit (modal popup) / search (product name)

Ty!

**Comment by Mortrest** [comment]
Hello
After creating a product, should create a product in stripe too?
I need product stripe id to save a sale in database for bought product after success pay.

**Comment by Mortrest** [comment]
Hello
This iteration almost completed but i have a question. add payment by stripe is for this iteration? post-sale endpoint is added. if I should implement payment too, how user buy a prodcut? one by one or we have shopping cart?

**Comment by app-generator** [comment]
Hello @Mortrest 

No shopping cart. Just a one-by-one purchase is provided. The most simple case, in other words.

The below sample has a working Stripe payment workflow (for Flask).

https://github.com/app-generator/sample-flask-stripe

Let me know if you need more information.
Ty!

**Comment by app-generator** [comment]
Hello @Mortrest, 
Please provide a status regarding the Stripe development. 
Ty!

P.S. in case you have time, please access you UpW account.

**Comment by app-generator** [comment]
Hello Guys, 

@Mortrest @mchoopani @SajjadKiani 

I've created a new project using the latest revision of this one. 
In case you have the time, please finish the development here: 

https://github.com/app-generator/django-soft-ui-dashboard-stripe

Edit invitations sent to all. 

Being a starter used in production, the changes saved on this repo will be deleted. 
We can migrate the code, once the feature is stable. 

Ty!

**Comment by app-generator** [comment]
P.S. here is the invitation:

https://github.com/app-generator/django-soft-ui-dashboard-stripe/invitations

🚀🚀

**Comment by Mortrest** [comment]
Hello
We added codes to mentioned repo.
Please take a look and tell us if some changes should be apply.

**Comment by app-generator** [comment]
Super @Mortrest, 

I'm on it. Ty

**Comment by app-generator** [comment]
P.S. @Mortrest  In case you have time for something new, ping me in UpW.
I would like to cook a fully-fledged NodeJS + react product (long-term, complete set of features)
🚀🚀
