### ISSUE TITLE
Form checkboxes are white on a white background...

### ISSUE THREAD

**Issue by petasis** [app-generator/django-soft-ui-dashboard#9]
Hi all,

I am using the SoftUI dashboard template, to render some tables (with django-tables2), where the first column is a list of checkboxes, to select the rows. The checkboxes are not visible, as unselected are white on white background.

If I check one, it renders as a black rectangle with rounded corners.

**Comment by BapJu** [comment]
I have the same problem,
I solved the problem temporarily by forcing the background-color.

``<input type="checkbox" name="profile_selection" value="{{ profile.id }}" class="form-check-input" style="background-color: #a8b8d8 !important;">``

**Comment by app-generator** [comment]
Hello guys! 

This issue comes from the UI library. I will open an associated issue:

https://github.com/app-generator/django-admin-soft-dashboard/issues/12

For live assistance, feel free to join the community: 

https://appseed.us/support/

TY!

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
